export function sanitizeNumber(value: string | number, min = 0, max = Infinity): number | null {
  const num = typeof value === 'string' ? parseFloat(value) : value;
  if (isNaN(num)) return null;
  if (num < min) return min;
  if (num > max) return max;
  return Math.round(num * 100) / 100;
}

export function sanitizePercentage(value: string | number): number | null {
  const num = typeof value === 'string' ? parseFloat(value) : value;
  if (isNaN(num)) return null;
  return Math.min(100, Math.max(0, num));
}

export function sanitizeText(value: string): string {
  if (!value) return '';
  return value
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#x27;')
    .trim()
    .slice(0, 500);
}

export function bucketValue(value: number, buckets: { max: number; label: string }[]): string {
  for (const bucket of buckets) {
    if (value <= bucket.max) {
      return bucket.label;
    }
  }
  return buckets[buckets.length - 1].label;
}

export const providerBuckets = [
  { max: 25, label: '<25' },
  { max: 50, label: '25-50' },
  { max: 100, label: '50-100' },
  { max: 200, label: '100-200' },
  { max: Infinity, label: '200+' },
];

export const encounterBuckets = [
  { max: 50000, label: '<50k' },
  { max: 100000, label: '50k-100k' },
  { max: 200000, label: '100k-200k' },
  { max: 500000, label: '200k-500k' },
  { max: Infinity, label: '500k+' },
];

export const gapBuckets = [
  { max: 100000, label: '<$100k' },
  { max: 250000, label: '$100k-$250k' },
  { max: 500000, label: '$250k-$500k' },
  { max: 1000000, label: '$500k-$1M' },
  { max: Infinity, label: '$1M+' },
];

export function clearAllStoredData(): void {
  sessionStorage.clear();
  localStorage.removeItem('roiCalculatorData');
}

export function generateResultsSummary(data: {
  annualGap?: number;
  realizationScore?: number;
  threeYearGap?: number;
  flow?: string;
}): string {
  const formatCurrency = (val: number) => 
    new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(val);
  
  return `
ROI Calculator Results
─────────────────────
${data.annualGap ? `Annual Gap: ${formatCurrency(data.annualGap)}` : ''}
${data.realizationScore ? `Realization Score: ${data.realizationScore}%` : ''}
${data.threeYearGap ? `3-Year Gap: ${formatCurrency(data.threeYearGap)}` : ''}

Generated by Abridge ROI Calculator
  `.trim();
}

const rateLimiter = {
  calls: {} as Record<string, number[]>,
  
  canMakeCall(endpoint: string, maxCalls = 10, windowMs = 60000): boolean {
    const now = Date.now();
    const key = endpoint;
    
    if (!this.calls[key]) {
      this.calls[key] = [];
    }
    
    this.calls[key] = this.calls[key].filter(time => now - time < windowMs);
    
    if (this.calls[key].length >= maxCalls) {
      return false;
    }
    
    this.calls[key].push(now);
    return true;
  }
};

export { rateLimiter };
